<?php

namespace App\Services;

class CountriesService
{
    /**
     * Get all countries with their ISO codes and names
     * 
     * @return array
     */
    public static function getAllCountries(): array
    {
        return [
            'AF' => 'Afghanistan',
            'AL' => 'Albania',
            'DZ' => 'Algeria',
            'AS' => 'American Samoa',
            'AD' => 'Andorra',
            'AO' => 'Angola',
            'AI' => 'Anguilla',
            'AQ' => 'Antarctica',
            'AG' => 'Antigua and Barbuda',
            'AR' => 'Argentina',
            'AM' => 'Armenia',
            'AW' => 'Aruba',
            'AU' => 'Australia',
            'AT' => 'Austria',
            'AZ' => 'Azerbaijan',
            'BS' => 'Bahamas',
            'BH' => 'Bahrain',
            'BD' => 'Bangladesh',
            'BB' => 'Barbados',
            'BY' => 'Belarus',
            'BE' => 'Belgium',
            'BZ' => 'Belize',
            'BJ' => 'Benin',
            'BM' => 'Bermuda',
            'BT' => 'Bhutan',
            'BO' => 'Bolivia',
            'BA' => 'Bosnia and Herzegovina',
            'BW' => 'Botswana',
            'BV' => 'Bouvet Island',
            'BR' => 'Brazil',
            'IO' => 'British Indian Ocean Territory',
            'BN' => 'Brunei Darussalam',
            'BG' => 'Bulgaria',
            'BF' => 'Burkina Faso',
            'BI' => 'Burundi',
            'KH' => 'Cambodia',
            'CM' => 'Cameroon',
            'CA' => 'Canada',
            'CV' => 'Cape Verde',
            'KY' => 'Cayman Islands',
            'CF' => 'Central African Republic',
            'TD' => 'Chad',
            'CL' => 'Chile',
            'CN' => 'China',
            'CX' => 'Christmas Island',
            'CC' => 'Cocos (Keeling) Islands',
            'CO' => 'Colombia',
            'KM' => 'Comoros',
            'CG' => 'Congo',
            'CD' => 'Congo, Democratic Republic of the',
            'CK' => 'Cook Islands',
            'CR' => 'Costa Rica',
            'CI' => 'Côte d\'Ivoire',
            'HR' => 'Croatia',
            'CU' => 'Cuba',
            'CY' => 'Cyprus',
            'CZ' => 'Czech Republic',
            'DK' => 'Denmark',
            'DJ' => 'Djibouti',
            'DM' => 'Dominica',
            'DO' => 'Dominican Republic',
            'EC' => 'Ecuador',
            'EG' => 'Egypt',
            'SV' => 'El Salvador',
            'GQ' => 'Equatorial Guinea',
            'ER' => 'Eritrea',
            'EE' => 'Estonia',
            'ET' => 'Ethiopia',
            'FK' => 'Falkland Islands (Malvinas)',
            'FO' => 'Faroe Islands',
            'FJ' => 'Fiji',
            'FI' => 'Finland',
            'FR' => 'France',
            'GF' => 'French Guiana',
            'PF' => 'French Polynesia',
            'TF' => 'French Southern Territories',
            'GA' => 'Gabon',
            'GM' => 'Gambia',
            'GE' => 'Georgia',
            'DE' => 'Germany',
            'GH' => 'Ghana',
            'GI' => 'Gibraltar',
            'GR' => 'Greece',
            'GL' => 'Greenland',
            'GD' => 'Grenada',
            'GP' => 'Guadeloupe',
            'GU' => 'Guam',
            'GT' => 'Guatemala',
            'GG' => 'Guernsey',
            'GN' => 'Guinea',
            'GW' => 'Guinea-Bissau',
            'GY' => 'Guyana',
            'HT' => 'Haiti',
            'HM' => 'Heard Island and McDonald Islands',
            'VA' => 'Holy See (Vatican City State)',
            'HN' => 'Honduras',
            'HK' => 'Hong Kong',
            'HU' => 'Hungary',
            'IS' => 'Iceland',
            'IN' => 'India',
            'ID' => 'Indonesia',
            'IR' => 'Iran, Islamic Republic of',
            'IQ' => 'Iraq',
            'IE' => 'Ireland',
            'IM' => 'Isle of Man',
            'IL' => 'Israel',
            'IT' => 'Italy',
            'JM' => 'Jamaica',
            'JP' => 'Japan',
            'JE' => 'Jersey',
            'JO' => 'Jordan',
            'KZ' => 'Kazakhstan',
            'KE' => 'Kenya',
            'KI' => 'Kiribati',
            'KP' => 'Korea, Democratic People\'s Republic of',
            'KR' => 'Korea, Republic of',
            'KW' => 'Kuwait',
            'KG' => 'Kyrgyzstan',
            'LA' => 'Lao People\'s Democratic Republic',
            'LV' => 'Latvia',
            'LB' => 'Lebanon',
            'LS' => 'Lesotho',
            'LR' => 'Liberia',
            'LY' => 'Libya',
            'LI' => 'Liechtenstein',
            'LT' => 'Lithuania',
            'LU' => 'Luxembourg',
            'MO' => 'Macao',
            'MK' => 'Macedonia, the former Yugoslav Republic of',
            'MG' => 'Madagascar',
            'MW' => 'Malawi',
            'MY' => 'Malaysia',
            'MV' => 'Maldives',
            'ML' => 'Mali',
            'MT' => 'Malta',
            'MH' => 'Marshall Islands',
            'MQ' => 'Martinique',
            'MR' => 'Mauritania',
            'MU' => 'Mauritius',
            'YT' => 'Mayotte',
            'MX' => 'Mexico',
            'FM' => 'Micronesia, Federated States of',
            'MD' => 'Moldova, Republic of',
            'MC' => 'Monaco',
            'MN' => 'Mongolia',
            'ME' => 'Montenegro',
            'MS' => 'Montserrat',
            'MA' => 'Morocco',
            'MZ' => 'Mozambique',
            'MM' => 'Myanmar',
            'NA' => 'Namibia',
            'NR' => 'Nauru',
            'NP' => 'Nepal',
            'NL' => 'Netherlands',
            'NC' => 'New Caledonia',
            'NZ' => 'New Zealand',
            'NI' => 'Nicaragua',
            'NE' => 'Niger',
            'NG' => 'Nigeria',
            'NU' => 'Niue',
            'NF' => 'Norfolk Island',
            'MP' => 'Northern Mariana Islands',
            'NO' => 'Norway',
            'OM' => 'Oman',
            'PK' => 'Pakistan',
            'PW' => 'Palau',
            'PS' => 'Palestinian Territory, Occupied',
            'PA' => 'Panama',
            'PG' => 'Papua New Guinea',
            'PY' => 'Paraguay',
            'PE' => 'Peru',
            'PH' => 'Philippines',
            'PN' => 'Pitcairn',
            'PL' => 'Poland',
            'PT' => 'Portugal',
            'PR' => 'Puerto Rico',
            'QA' => 'Qatar',
            'RE' => 'Réunion',
            'RO' => 'Romania',
            'RU' => 'Russian Federation',
            'RW' => 'Rwanda',
            'BL' => 'Saint Barthélemy',
            'SH' => 'Saint Helena, Ascension and Tristan da Cunha',
            'KN' => 'Saint Kitts and Nevis',
            'LC' => 'Saint Lucia',
            'MF' => 'Saint Martin (French part)',
            'PM' => 'Saint Pierre and Miquelon',
            'VC' => 'Saint Vincent and the Grenadines',
            'WS' => 'Samoa',
            'SM' => 'San Marino',
            'ST' => 'Sao Tome and Principe',
            'SA' => 'Saudi Arabia',
            'SN' => 'Senegal',
            'RS' => 'Serbia',
            'SC' => 'Seychelles',
            'SL' => 'Sierra Leone',
            'SG' => 'Singapore',
            'SX' => 'Sint Maarten (Dutch part)',
            'SK' => 'Slovakia',
            'SI' => 'Slovenia',
            'SB' => 'Solomon Islands',
            'SO' => 'Somalia',
            'ZA' => 'South Africa',
            'GS' => 'South Georgia and the South Sandwich Islands',
            'SS' => 'South Sudan',
            'ES' => 'Spain',
            'LK' => 'Sri Lanka',
            'SD' => 'Sudan',
            'SR' => 'Suriname',
            'SJ' => 'Svalbard and Jan Mayen',
            'SZ' => 'Swaziland',
            'SE' => 'Sweden',
            'CH' => 'Switzerland',
            'SY' => 'Syrian Arab Republic',
            'TW' => 'Taiwan, Province of China',
            'TJ' => 'Tajikistan',
            'TZ' => 'Tanzania, United Republic of',
            'TH' => 'Thailand',
            'TL' => 'Timor-Leste',
            'TG' => 'Togo',
            'TK' => 'Tokelau',
            'TO' => 'Tonga',
            'TT' => 'Trinidad and Tobago',
            'TN' => 'Tunisia',
            'TR' => 'Turkey',
            'TM' => 'Turkmenistan',
            'TC' => 'Turks and Caicos Islands',
            'TV' => 'Tuvalu',
            'UG' => 'Uganda',
            'UA' => 'Ukraine',
            'AE' => 'United Arab Emirates',
            'GB' => 'United Kingdom',
            'US' => 'United States',
            'UM' => 'United States Minor Outlying Islands',
            'UY' => 'Uruguay',
            'UZ' => 'Uzbekistan',
            'VU' => 'Vanuatu',
            'VE' => 'Venezuela, Bolivarian Republic of',
            'VN' => 'Viet Nam',
            'VG' => 'Virgin Islands, British',
            'VI' => 'Virgin Islands, U.S.',
            'WF' => 'Wallis and Futuna',
            'EH' => 'Western Sahara',
            'YE' => 'Yemen',
            'ZM' => 'Zambia',
            'ZW' => 'Zimbabwe',
        ];
    }

    /**
     * Get countries grouped by region for better organization
     * 
     * @return array
     */
    public static function getCountriesByRegion(): array
    {
        return [
            'North America' => [
                'US' => 'United States',
                'CA' => 'Canada',
                'MX' => 'Mexico',
                'GT' => 'Guatemala',
                'BZ' => 'Belize',
                'SV' => 'El Salvador',
                'HN' => 'Honduras',
                'NI' => 'Nicaragua',
                'CR' => 'Costa Rica',
                'PA' => 'Panama',
                'CU' => 'Cuba',
                'JM' => 'Jamaica',
                'HT' => 'Haiti',
                'DO' => 'Dominican Republic',
                'TT' => 'Trinidad and Tobago',
                'BB' => 'Barbados',
                'AG' => 'Antigua and Barbuda',
                'BS' => 'Bahamas',
                'DM' => 'Dominica',
                'GD' => 'Grenada',
                'KN' => 'Saint Kitts and Nevis',
                'LC' => 'Saint Lucia',
                'VC' => 'Saint Vincent and the Grenadines',
            ],
            'Europe' => [
                'GB' => 'United Kingdom',
                'DE' => 'Germany',
                'FR' => 'France',
                'IT' => 'Italy',
                'ES' => 'Spain',
                'NL' => 'Netherlands',
                'BE' => 'Belgium',
                'AT' => 'Austria',
                'CH' => 'Switzerland',
                'SE' => 'Sweden',
                'NO' => 'Norway',
                'DK' => 'Denmark',
                'FI' => 'Finland',
                'IE' => 'Ireland',
                'PT' => 'Portugal',
                'GR' => 'Greece',
                'PL' => 'Poland',
                'CZ' => 'Czech Republic',
                'HU' => 'Hungary',
                'RO' => 'Romania',
                'BG' => 'Bulgaria',
                'HR' => 'Croatia',
                'SI' => 'Slovenia',
                'SK' => 'Slovakia',
                'LT' => 'Lithuania',
                'LV' => 'Latvia',
                'EE' => 'Estonia',
                'LU' => 'Luxembourg',
                'MT' => 'Malta',
                'CY' => 'Cyprus',
                'IS' => 'Iceland',
                'LI' => 'Liechtenstein',
                'MC' => 'Monaco',
                'SM' => 'San Marino',
                'VA' => 'Holy See (Vatican City State)',
                'AD' => 'Andorra',
                'AL' => 'Albania',
                'BA' => 'Bosnia and Herzegovina',
                'ME' => 'Montenegro',
                'MK' => 'Macedonia, the former Yugoslav Republic of',
                'RS' => 'Serbia',
                'UA' => 'Ukraine',
                'BY' => 'Belarus',
                'MD' => 'Moldova, Republic of',
                'RU' => 'Russian Federation',
            ],
            'Asia' => [
                'CN' => 'China',
                'JP' => 'Japan',
                'KR' => 'Korea, Republic of',
                'IN' => 'India',
                'ID' => 'Indonesia',
                'TH' => 'Thailand',
                'VN' => 'Viet Nam',
                'MY' => 'Malaysia',
                'SG' => 'Singapore',
                'PH' => 'Philippines',
                'BD' => 'Bangladesh',
                'PK' => 'Pakistan',
                'LK' => 'Sri Lanka',
                'NP' => 'Nepal',
                'BT' => 'Bhutan',
                'MV' => 'Maldives',
                'MM' => 'Myanmar',
                'LA' => 'Lao People\'s Democratic Republic',
                'KH' => 'Cambodia',
                'MN' => 'Mongolia',
                'KZ' => 'Kazakhstan',
                'UZ' => 'Uzbekistan',
                'KG' => 'Kyrgyzstan',
                'TJ' => 'Tajikistan',
                'TM' => 'Turkmenistan',
                'AF' => 'Afghanistan',
                'IR' => 'Iran, Islamic Republic of',
                'IQ' => 'Iraq',
                'SY' => 'Syrian Arab Republic',
                'TR' => 'Turkey',
                'GE' => 'Georgia',
                'AM' => 'Armenia',
                'AZ' => 'Azerbaijan',
                'IL' => 'Israel',
                'JO' => 'Jordan',
                'LB' => 'Lebanon',
                'SA' => 'Saudi Arabia',
                'AE' => 'United Arab Emirates',
                'QA' => 'Qatar',
                'BH' => 'Bahrain',
                'KW' => 'Kuwait',
                'OM' => 'Oman',
                'YE' => 'Yemen',
                'TW' => 'Taiwan, Province of China',
                'HK' => 'Hong Kong',
                'MO' => 'Macao',
                'BN' => 'Brunei Darussalam',
                'TL' => 'Timor-Leste',
            ],
            'Africa' => [
                'ZA' => 'South Africa',
                'NG' => 'Nigeria',
                'EG' => 'Egypt',
                'KE' => 'Kenya',
                'ET' => 'Ethiopia',
                'GH' => 'Ghana',
                'MA' => 'Morocco',
                'TN' => 'Tunisia',
                'DZ' => 'Algeria',
                'LY' => 'Libya',
                'SD' => 'Sudan',
                'SS' => 'South Sudan',
                'UG' => 'Uganda',
                'TZ' => 'Tanzania, United Republic of',
                'ZW' => 'Zimbabwe',
                'ZM' => 'Zambia',
                'BW' => 'Botswana',
                'NA' => 'Namibia',
                'SZ' => 'Swaziland',
                'LS' => 'Lesotho',
                'MG' => 'Madagascar',
                'MU' => 'Mauritius',
                'SC' => 'Seychelles',
                'KM' => 'Comoros',
                'YT' => 'Mayotte',
                'RE' => 'Réunion',
                'MZ' => 'Mozambique',
                'MW' => 'Malawi',
                'ZM' => 'Zambia',
                'AO' => 'Angola',
                'CD' => 'Congo, Democratic Republic of the',
                'CG' => 'Congo',
                'CF' => 'Central African Republic',
                'TD' => 'Chad',
                'CM' => 'Cameroon',
                'GQ' => 'Equatorial Guinea',
                'GA' => 'Gabon',
                'ST' => 'Sao Tome and Principe',
                'CV' => 'Cape Verde',
                'SN' => 'Senegal',
                'GM' => 'Gambia',
                'GW' => 'Guinea-Bissau',
                'GN' => 'Guinea',
                'SL' => 'Sierra Leone',
                'LR' => 'Liberia',
                'CI' => 'Côte d\'Ivoire',
                'GH' => 'Ghana',
                'TG' => 'Togo',
                'BJ' => 'Benin',
                'NE' => 'Niger',
                'BF' => 'Burkina Faso',
                'ML' => 'Mali',
                'MR' => 'Mauritania',
                'ER' => 'Eritrea',
                'DJ' => 'Djibouti',
                'SO' => 'Somalia',
                'RW' => 'Rwanda',
                'BI' => 'Burundi',
            ],
            'Oceania' => [
                'AU' => 'Australia',
                'NZ' => 'New Zealand',
                'FJ' => 'Fiji',
                'PG' => 'Papua New Guinea',
                'SB' => 'Solomon Islands',
                'VU' => 'Vanuatu',
                'NC' => 'New Caledonia',
                'PF' => 'French Polynesia',
                'WS' => 'Samoa',
                'TO' => 'Tonga',
                'KI' => 'Kiribati',
                'TV' => 'Tuvalu',
                'NR' => 'Nauru',
                'PW' => 'Palau',
                'FM' => 'Micronesia, Federated States of',
                'MH' => 'Marshall Islands',
                'CK' => 'Cook Islands',
                'NU' => 'Niue',
                'TK' => 'Tokelau',
                'AS' => 'American Samoa',
                'GU' => 'Guam',
                'MP' => 'Northern Mariana Islands',
                'VI' => 'Virgin Islands, U.S.',
                'WF' => 'Wallis and Futuna',
            ],
            'South America' => [
                'BR' => 'Brazil',
                'AR' => 'Argentina',
                'CL' => 'Chile',
                'CO' => 'Colombia',
                'PE' => 'Peru',
                'VE' => 'Venezuela, Bolivarian Republic of',
                'EC' => 'Ecuador',
                'BO' => 'Bolivia',
                'PY' => 'Paraguay',
                'UY' => 'Uruguay',
                'GY' => 'Guyana',
                'SR' => 'Suriname',
                'FK' => 'Falkland Islands (Malvinas)',
            ],
        ];
    }

    /**
     * Get popular countries (most commonly used)
     * 
     * @return array
     */
    public static function getPopularCountries(): array
    {
        return [
            'US' => 'United States',
            'CA' => 'Canada',
            'GB' => 'United Kingdom',
            'AU' => 'Australia',
            'DE' => 'Germany',
            'FR' => 'France',
            'IT' => 'Italy',
            'ES' => 'Spain',
            'NL' => 'Netherlands',
            'BE' => 'Belgium',
            'AT' => 'Austria',
            'CH' => 'Switzerland',
            'SE' => 'Sweden',
            'NO' => 'Norway',
            'DK' => 'Denmark',
            'FI' => 'Finland',
            'IE' => 'Ireland',
            'PT' => 'Portugal',
            'GR' => 'Greece',
            'PL' => 'Poland',
            'CZ' => 'Czech Republic',
            'HU' => 'Hungary',
            'RO' => 'Romania',
            'BG' => 'Bulgaria',
            'HR' => 'Croatia',
            'SI' => 'Slovenia',
            'SK' => 'Slovakia',
            'LT' => 'Lithuania',
            'LV' => 'Latvia',
            'EE' => 'Estonia',
            'LU' => 'Luxembourg',
            'MT' => 'Malta',
            'CY' => 'Cyprus',
            'IS' => 'Iceland',
            'CN' => 'China',
            'JP' => 'Japan',
            'KR' => 'Korea, Republic of',
            'IN' => 'India',
            'ID' => 'Indonesia',
            'TH' => 'Thailand',
            'VN' => 'Viet Nam',
            'MY' => 'Malaysia',
            'SG' => 'Singapore',
            'PH' => 'Philippines',
            'BD' => 'Bangladesh',
            'PK' => 'Pakistan',
            'LK' => 'Sri Lanka',
            'NP' => 'Nepal',
            'BT' => 'Bhutan',
            'MV' => 'Maldives',
            'MM' => 'Myanmar',
            'LA' => 'Lao People\'s Democratic Republic',
            'KH' => 'Cambodia',
            'MN' => 'Mongolia',
            'KZ' => 'Kazakhstan',
            'UZ' => 'Uzbekistan',
            'KG' => 'Kyrgyzstan',
            'TJ' => 'Tajikistan',
            'TM' => 'Turkmenistan',
            'AF' => 'Afghanistan',
            'IR' => 'Iran, Islamic Republic of',
            'IQ' => 'Iraq',
            'SY' => 'Syrian Arab Republic',
            'TR' => 'Turkey',
            'GE' => 'Georgia',
            'AM' => 'Armenia',
            'AZ' => 'Azerbaijan',
            'IL' => 'Israel',
            'JO' => 'Jordan',
            'LB' => 'Lebanon',
            'SA' => 'Saudi Arabia',
            'AE' => 'United Arab Emirates',
            'QA' => 'Qatar',
            'BH' => 'Bahrain',
            'KW' => 'Kuwait',
            'OM' => 'Oman',
            'YE' => 'Yemen',
            'TW' => 'Taiwan, Province of China',
            'HK' => 'Hong Kong',
            'MO' => 'Macao',
            'BN' => 'Brunei Darussalam',
            'TL' => 'Timor-Leste',
            'ZA' => 'South Africa',
            'NG' => 'Nigeria',
            'EG' => 'Egypt',
            'KE' => 'Kenya',
            'ET' => 'Ethiopia',
            'GH' => 'Ghana',
            'MA' => 'Morocco',
            'TN' => 'Tunisia',
            'DZ' => 'Algeria',
            'LY' => 'Libya',
            'SD' => 'Sudan',
            'SS' => 'South Sudan',
            'UG' => 'Uganda',
            'TZ' => 'Tanzania, United Republic of',
            'ZW' => 'Zimbabwe',
            'ZM' => 'Zambia',
            'BW' => 'Botswana',
            'NA' => 'Namibia',
            'SZ' => 'Swaziland',
            'LS' => 'Lesotho',
            'MG' => 'Madagascar',
            'MU' => 'Mauritius',
            'SC' => 'Seychelles',
            'KM' => 'Comoros',
            'YT' => 'Mayotte',
            'RE' => 'Réunion',
            'MZ' => 'Mozambique',
            'MW' => 'Malawi',
            'ZM' => 'Zambia',
            'AO' => 'Angola',
            'CD' => 'Congo, Democratic Republic of the',
            'CG' => 'Congo',
            'CF' => 'Central African Republic',
            'TD' => 'Chad',
            'CM' => 'Cameroon',
            'GQ' => 'Equatorial Guinea',
            'GA' => 'Gabon',
            'ST' => 'Sao Tome and Principe',
            'CV' => 'Cape Verde',
            'SN' => 'Senegal',
            'GM' => 'Gambia',
            'GW' => 'Guinea-Bissau',
            'GN' => 'Guinea',
            'SL' => 'Sierra Leone',
            'LR' => 'Liberia',
            'CI' => 'Côte d\'Ivoire',
            'GH' => 'Ghana',
            'TG' => 'Togo',
            'BJ' => 'Benin',
            'NE' => 'Niger',
            'BF' => 'Burkina Faso',
            'ML' => 'Mali',
            'MR' => 'Mauritania',
            'ER' => 'Eritrea',
            'DJ' => 'Djibouti',
            'SO' => 'Somalia',
            'RW' => 'Rwanda',
            'BI' => 'Burundi',
            'BR' => 'Brazil',
            'AR' => 'Argentina',
            'CL' => 'Chile',
            'CO' => 'Colombia',
            'PE' => 'Peru',
            'VE' => 'Venezuela, Bolivarian Republic of',
            'EC' => 'Ecuador',
            'BO' => 'Bolivia',
            'PY' => 'Paraguay',
            'UY' => 'Uruguay',
            'GY' => 'Guyana',
            'SR' => 'Suriname',
            'FK' => 'Falkland Islands (Malvinas)',
        ];
    }

    /**
     * Get country name by ISO code
     * 
     * @param string $code
     * @return string|null
     */
    public static function getCountryName(string $code): ?string
    {
        $countries = self::getAllCountries();
        return $countries[$code] ?? null;
    }

    /**
     * Get ISO code by country name
     * 
     * @param string $name
     * @return string|null
     */
    public static function getCountryCode(string $name): ?string
    {
        $countries = self::getAllCountries();
        return array_search($name, $countries) ?: null;
    }

    /**
     * Search countries by name
     * 
     * @param string $query
     * @return array
     */
    public static function searchCountries(string $query): array
    {
        $countries = self::getAllCountries();
        $query = strtolower($query);
        
        return array_filter($countries, function ($name) use ($query) {
            return strpos(strtolower($name), $query) !== false;
        });
    }
}
